name: pythonChecks

on: [push, pull_request]

jobs:
  codestyle-black:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repository state
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dev depencies using pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev
      - name: Check codestyle with black
        run: pipenv run black --check -l 80 ./python

  sorted-imports:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repository state
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dev dependencies using pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev
      - name: Check import order with isort
        run: pipenv run isort ./python --recursive --diff

  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repository state
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dev depencies using pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev
      - name: Lint using flake8
        run: |
          files=$(find ./python -type f -name "*.py")
          for file in $files; do
            pipenv run flake8 $file
          done
  type-annotations:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repository state
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dev depencies using pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev
      - name: Lint using mypy
        run: pipenv run mypy --namespace-packages ./python
