name: pythonChecks

on: [push, pull_request]

jobs:
  codestyle-black:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repository state
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dev depencies using pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev --python 3.7
      - name: Check codestyle with black
        run: pipenv run black --check -l 80 ./utilBot

  sorted-imports:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repository state
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dev dependencies using pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev --python 3.7
      - name: Check import order with isort
        run: pipenv run isort ./utilBot --recursive --diff

  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repository state
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dev depencies using pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev --python 3.7
      - name: Lint using flake8
        run: |
          files=$(find ./utilBot -type f -name "*.py")
          for file in $files; do
            pipenv run flake8 $file
          done
  type-annotations:
    runs-on: ubuntu-latest
    steps:
      - name: Check out current repository state
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dev depencies using pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev --python 3.7
      - name: Lint using mypy
        run: pipenv run mypy --namespace-packages ./utilBot
